const $=s=>document.querySelector(s);
let phase=0,scenario='overflow',paused=false,stream=null,cameraPending=false;
const history=[];
function content(){
 if(phase===0)return ['准备好了就开始','我们先检查口红。','按下开始体验，听取取景提示。演示会模拟检查结果，带你走完一次修正流程。','开始体验','等待开始'];
 if(phase===1)return ['01 / 取景准备','把手机放稳，面向镜头。','让光线均匀照在脸上，嘴唇自然闭合。准备好后，按下“模拟检查”。','模拟检查','等待你确认取景'];
 if(phase===2&&scenario==='uncertain')return ['02 / 模拟检查','光线不足，暂时无法判断。','请移到正面均匀照明的位置，避免背光。本场景不会输出口红是否合格的结论。','重新准备取景','演示：拒绝判断'];
 if(phase===2&&scenario==='clear')return ['02 / 模拟检查','未见明显唇线外溢。','这是预设的“未见明显问题”结果。真实产品需要通过摄像头检测，并经过不同光照与肤色测试。','完成本次演示','演示：未见明显问题'];
 if(phase===2)return ['02 / 模拟检查','你的右侧嘴角，需要处理一处。','演示结果：你自己的右侧嘴角有少量口红超出唇线。下一步会给出一条修正提示。','听取修正提示','演示：发现一处外溢'];
 if(phase===3)return ['03 / 语音纠正','轻轻处理右侧嘴角的外溢。','以你自己的右侧为准。用干净棉签轻轻擦去唇线外多余口红；完成后放下工具，再按“模拟复查”。','已调整，模拟复查','一次只处理这一处'];
 if(phase===4)return ['04 / 模拟复查','这一次，外溢已改善。','预设复查结果：刚才提示的外溢已改善。这展示了纠正流程，不代表系统分析了摄像头画面。','完成本次演示','演示：复查完成'];
 return ['本次演示完成','你已完成这次口红检查。','真实产品的下一步，是验证这些指令是否清楚、用户是否能独立修正，以及视觉结果是否可靠。','再体验一次','流程完成'];
}
let speechVersion=0;
function stopSpeech(){speechVersion++;document.body.classList.remove('speaking');if('speechSynthesis'in window)speechSynthesis.cancel()}
function speak(){stopSpeech();if(!$('#voice').checked||paused)return;if(!('speechSynthesis'in window)){ $('#voice-status').textContent='此浏览器不支持语音播报，请使用文字提示。';return; }const current=speechVersion,c=content(),u=new SpeechSynthesisUtterance(c[1]+' '+c[2]);u.lang='zh-CN';u.rate=Number($('#speed')?.value||.9);u.onstart=()=>{if(current!==speechVersion)return;document.body.classList.add('speaking');$('#voice-status').textContent='正在播报当前提示…'};u.onend=()=>{if(current!==speechVersion)return;document.body.classList.remove('speaking');$('#voice-status').textContent='播报结束，需要时可以重听。'};u.onerror=()=>{if(current!==speechVersion)return;document.body.classList.remove('speaking');$('#voice-status').textContent='语音未能播出，可重听或使用文字提示。'};speechSynthesis.speak(u);}
function render(announce=false){const c=content();$('#step-label').textContent=c[0];$('#instruction-title').textContent=paused?'体验已暂停':c[1];$('#instruction-body').textContent=paused?'按“继续体验”回到当前步骤。摄像头可通过左侧按钮单独关闭。':c[2];$('#next').textContent=c[3];$('#next').disabled=paused;$('#result-label').textContent=paused?'已暂停':c[4];$('#pause').textContent=paused?'继续体验':'暂停体验';$('#pause').setAttribute('aria-pressed',String(paused));const stage=phase<=1?0:phase===2?1:phase===3?2:3;document.querySelectorAll('[data-stage]').forEach(el=>{el.removeAttribute('aria-current');if(Number(el.dataset.stage)===stage)el.setAttribute('aria-current','step')});$('#history').replaceChildren();(history.length?history:['等待体验开始。所有记录只保留在当前页面。']).forEach(t=>{const li=document.createElement('li');li.textContent=t;$('#history').append(li)});if(announce)speak();}
function advance(){if(paused)return;if(phase===5)return reset(true);if(phase===2&&scenario==='uncertain'){phase=1;}else if(phase===2&&scenario==='clear'){phase=5;}else phase++;history.push(content()[1]);render(true)}
function reset(announce=false){stopSpeech();phase=0;paused=false;history.length=0;render(announce)}
$('#next').addEventListener('click',advance);$('#repeat').addEventListener('click',speak);$('#restart').addEventListener('click',()=>reset(true));$('#pause').addEventListener('click',()=>{paused=!paused;stopSpeech();render(!paused)});$('#voice').addEventListener('change',()=>{if($('#voice').checked)speak();else{stopSpeech();$('#voice-status').textContent='语音已关闭，文字提示仍可使用。'}});$('#large').addEventListener('click',()=>{const active=document.documentElement.classList.toggle('large');$('#large').setAttribute('aria-pressed',String(active));$('#large').textContent=active?'标准字号':'大字模式'});document.querySelectorAll('[name=scenario]').forEach(el=>el.addEventListener('change',()=>{scenario=el.value;reset(false)}));
function closeCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;$('#video').srcObject=null;$('#video').style.display='none';$('#camera-empty').hidden=false;$('#camera-state').textContent='摄像头已关闭';$('#camera-button').textContent='开启摄像头预览';$('#camera-message').textContent='摄像头已关闭，可继续体验演示。'}
$('#camera-button').addEventListener('click',async()=>{if(stream)return closeCamera();if(cameraPending)return;if(!navigator.mediaDevices?.getUserMedia){$('#camera-message').textContent='当前环境不支持摄像头预览，请使用演示。';return}cameraPending=true;$('#camera-button').disabled=true;$('#camera-message').textContent='等待你允许摄像头访问…';try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});$('#video').srcObject=stream;await $('#video').play();$('#video').style.display='block';$('#camera-empty').hidden=true;$('#camera-state').textContent='本地预览中';$('#camera-button').textContent='关闭摄像头';$('#camera-message').textContent='画面仅供本机预览；检查结果仍为预设演示。';}catch(e){closeCamera();$('#camera-message').textContent=e.name==='NotAllowedError'?'摄像头权限未开启，可继续使用演示。':'未能打开摄像头，请检查设备或继续使用演示。';}finally{cameraPending=false;$('#camera-button').disabled=false}});
window.addEventListener('pagehide',()=>{stopSpeech();closeCamera()});render();
